### PR TITLE
open sockets before making servers

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
This is the first step to change the user.

### CODE REVIEW

**Comment by khibino** [comment]
I want to add the service name to the error information
https://github.com/kazu-yamamoto/dnsext/commit/error-info-srv

**Comment by khibino** [comment]
DoT does not work

```
dug: HandshakeFailed (Error_Protocol "expecting server hello, got alert : [(AlertLevel_Fatal,NoApplicationProtocol)]" HandshakeFailure)
```

**Review by khibino — COMMENTED** [review]
DoT does not work

```
dug: HandshakeFailed (Error_Protocol "expecting server hello, got alert : [(AlertLevel_Fatal,NoApplicationProtocol)]" HandshakeFailure)
```

**Comment by khibino** [comment]
Ah, it was a careless change.
Fixed in https://github.com/kazu-yamamoto/dnsext/commit/a9ddcf5a28d5e05cf8033d31c47003aa78d8b17a

https://github.com/kazu-yamamoto/dnsext/commit/681171c3322837c0aaa55e1677e74d6dd79abd98#commitcomment-144318279

**Review by khibino — APPROVED** [review]

**Comment by kazu-yamamoto** [comment]
Merged with your commits.
Thanks.

**Pull request merged**
