### PR TITLE
Fourmolu

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
What do you think this coding style?

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
I also formatted `full-resolver`.

**Comment by kazu-yamamoto** [comment]
We can do this conversion by `find . -name "*.hs" | xargs fourmolu -i` in the top directory.

**Comment by khibino** [comment]
What revision of fourmolu did you use to do this formatting?

**Comment by kazu-yamamoto** [comment]
```
% fourmolu --version
fourmolu 0.12.0.0
using ghc-lib-parser 9.6.2.20230523
```

**Pull request merged**
