### PR TITLE
Result safe merge

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
This should implement atomic printing.

### CODE REVIEW

**Comment by khibino** [comment]
The results order are displayed changes in the order given on the command line, rather than the order finished, but the implementation is simpler.
What do you think?

https://github.com/kazu-yamamoto/dnsext/commit/578467e361c89a01d3f30d264a77f6012bcebf40

**Review by khibino — COMMENTED** [review]
The results order are displayed changes in the order given on the command line, rather than the order finished, but the implementation is simpler.
What do you think?

https://github.com/kazu-yamamoto/dnsext/commit/578467e361c89a01d3f30d264a77f6012bcebf40

**Review by khibino — COMMENTED** [review]
Connections were included in the `PipelineResolver` continuations, so update impl to share them.

https://github.com/kazu-yamamoto/dnsext/commit/47977af94ba394e3aa8b0f00ac5c0a76ab6ea737

**Comment by kazu-yamamoto** [comment]
This PR has been merged.
Let's continue the discussion in #175.

**Pull request closed without merging**
