### PR TITLE
Separate print result

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
Using STM log for atomicity.

### CODE REVIEW

**Review by khibino — COMMENTED** [review]
Multiple threads may execute printResultSTM with the same result,
like following event sequence:

```
thread1: read `False` from tvar
thread2: read `False` from tvar
thread1: run `printResultSTM`
thread2: run `printResultSTM`
...
```

**Comment by khibino** [comment]
> 
> Multiple threads may execute printResultSTM with the same result, like following event sequence:

By `putTMVar` from the thread that outputs the results, make others wait.

https://github.com/kazu-yamamoto/dnsext/commit/fe0a206f3479321682cf0ca326e0952340add18e

**Comment by kazu-yamamoto** [comment]
Ah! Thanks.
Let's merge.

**Comment by kazu-yamamoto** [comment]
> thread1: read `False` from tvar
> thread2: read `False` from tvar
> thread1: run `printResultSTM`
> thread2: run `printResultSTM`
> thread1: write True to tvar
> thread2: write True to tvar

This never happens because STM actions run atomically.
Reverting fe0a206.

**Comment by khibino** [comment]
> ```
> thread1: read `False` from tvar
> thread2: read `False` from tvar
> thread1: run `printResultSTM`
> thread2: run `printResultSTM`
> thread1: write True to tvar
> thread2: write True to tvar
> ```

Sorry.
When thread2 does `printResultSTM`, it knows it broke thread1's transaction, so thread2 retries.
So the original program is safe.

**Pull request merged**
